BASE_TASK_CONFIG_PATH: habitat_extensions/config/vlnce_task_aug.yaml
SIMULATOR_GPU_ID: 0
TORCH_GPU_ID: 0
NUM_PROCESSES: 5
TENSORBOARD_DIR: data/tensorboard_dirs/cma_aug
CHECKPOINT_FOLDER: data/checkpoints/cma_aug
EVAL_CKPT_PATH_DIR: data/checkpoints/cma_aug

SENSORS: ['RGB_SENSOR', 'DEPTH_SENSOR']

EVAL:
  USE_CKPT_CONFIG: False
  SPLIT: val_unseen
  EPISODE_COUNT: 50000

DAGGER:
  ITERATIONS: 1
  EPOCHS: 30
  UPDATE_SIZE: 157232
  BATCH_SIZE: 8
  P: 1.0
  PRELOAD_LMDB_FEATURES: False
  LMDB_FEATURES_DIR: /mnt/cephfs/dataset/VLN-CE/result/jidongyu/_train_seen_data/trajectories.lmdb

same_level_train: False
